name: deep_link_client
description: A Dart package which provides a deep link stream
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_core: ^2.1.1
  firebase_dynamic_links: ^5.0.3
  plugin_platform_interface: ^2.1.3
  rxdart: ^0.27.3
  very_good_analysis: ^4.0.0

dev_dependencies:
  firebase_core_platform_interface: ^4.5.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
