name: notifications_client
description: A Generic Notifications Client Interface.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4
  very_good_analysis: ^4.0.0
