name: news_blocks_ui
description: A Flutter package that contains UI components for news blocks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_ui:
    path: ../app_ui
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  google_mobile_ads: ^3.0.0
  news_blocks:
    path: ../../api/packages/news_blocks
  path_provider_platform_interface: ^2.0.5
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.3
  url_launcher: ^6.1.7
  url_launcher_platform_interface: ^2.1.1
  video_player: ^2.4.2
  video_player_platform_interface: ^6.0.1

dev_dependencies:
  build_runner: ^2.0.3
  fake_async: ^1.3.0
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
