name: in_app_purchase_repository
description: A repository that manages user purchase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  the_daily_israel_api:
    path: ../../api
  in_app_purchase: ^3.0.6

dev_dependencies:
  coverage: ^1.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^4.0.0
