name: news_repository
description: A repository that exposes news data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  the_daily_israel_api:
    path: ../../api

dev_dependencies:
  coverage: ^1.2.0
  mocktail: ^1.0.0
  test: ^1.21.4
  very_good_analysis: ^4.0.0
