name: purchase_client
description: A PurchaseClient stubbing InAppPurchase implementation.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  in_app_purchase: ^3.0.5
  in_app_purchase_platform_interface: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
