name: article_repository
description: A repository that manages article data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  equatable: ^2.0.3
  the_daily_israel_api:
    path: ../../api
  storage:
    path: ../storage/storage

dev_dependencies:
  coverage: ^1.3.2
  mocktail: ^1.0.1
  test: ^1.21.4
  very_good_analysis: ^4.0.0
