name: news_blocks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "api/packages/news_blocks/**"
      - ".github/workflows/news_blocks.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart"
      dart_sdk: 2.19.2
      working_directory: api/packages/news_blocks
